MvcIBF/Controllers/VODsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcIBF.Data;
using MvcIBF.Models;
using MvcIBF.Repository.IRepository;

namespace MvcIBF.Controllers
{
    public class VODsController : Controller
    {
        private readonly IVODRepository _context;

        public VODsController(IVODRepository context)
        {
            _context = context;
        }

        // GET: VODs
        public  IActionResult Index()
        {
            IEnumerable<VOD> vodsList = _context.GetAll();
            return View(vodsList);
        }

        // GET: VODs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.GetAll == null)
            {
                return NotFound();
            }

            var vOD =  _context
                .GetFirstOrDefault(m => m.VodId == id);
            if (vOD == null)
            {
                return NotFound();
            }

            return View(vOD);
        }

        // GET: VODs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VODs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VodId,VodName")] VOD vOD)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vOD);
                _context.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(vOD);
        }

        // GET: VODs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.GetAll() == null)
            {
                return NotFound();
            }

            var vOD = _context
               .GetFirstOrDefault(m => m.VodId == id);
            if (vOD == null)
            {
                return NotFound();
            }
            return View(vOD);
        }

        // POST: VODs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VodId,VodName")] VOD vOD)
        {
            if (id != vOD.VodId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vOD);
                    _context.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VODExists(vOD.VodId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vOD);
        }

        // GET: VODs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.GetAll == null)
            {
                return NotFound();
            }

            var vOD = _context
                .GetFirstOrDefault(m => m.VodId == id);
            if (vOD == null)
            {
                return NotFound();
            }

            return View(vOD);
        }

        // POST: VODs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.GetAll == null)
            {
                return Problem("Entity set 'MvcIBFContext.VODs'  is null.");
            }
            var vOD = _context
                .GetFirstOrDefault(m => m.VodId == id);
            if (vOD != null)
            {
                _context.Remove(vOD);
            }

            _context.Save();
            return RedirectToAction(nameof(Index));
        }
        
        private bool VODExists(int id)
        {
            return _context.GetAll().Any(e => e.VodId == id);
        }
        
    }
}

MvcIBF/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IBF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (!User.Identity.IsAuthenticated)
                        {
                            <a class="navbar-brand" asp-area="Guest" asp-controller="Movies" asp-action="Index">IBF</a>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Guest" asp-controller="Movies" asp-action="Index">Filmy</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Guest" asp-controller="Stars" asp-action="Index">Gwiazdy</a>
                            </li>

                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="navbar-brand" asp-area="Admin" asp-controller="Movies" asp-action="Index">IBF</a>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Admin" asp-controller="Movies" asp-action="Index">Filmy</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Admin" asp-controller="VODs" asp-action="Index">VOD</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Admin" asp-controller="Moods" asp-action="Index">Nastroje</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Admin" asp-controller="Genres" asp-action="Index">Gatunki</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Admin" asp-controller="Countries" asp-action="Index">Kraje</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Admin" asp-controller="Stars" asp-action="Index">Gwiazdy</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Admin" asp-controller="Functions" asp-action="Index">Funkcje</a>
                            </li>                            
                             <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="UsersDropdown" role="button" data-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
                                    Zarządzaj użytkownikami
                                </a>
                                <div class="dropdown-menu" aria-labelledby="UsersDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="Index">Usuń użytkownika</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="IndexModeratorsAdd">Nadaj uprawnienia</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="IndexModeratorsDelete">Zabierz uprawnienia</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="friendshipDropdown" role="button" data-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
                                    Znajomi
                                </a>
                                <div class="dropdown-menu" aria-labelledby="friendshipDropdown">
                                    <a class="dropdown-item" asp-area="User" asp-controller="Friendships" asp-action="Index">Szukaj znajomego</a>
                                    <a class="dropdown-item" asp-area="User" asp-controller="Friendships" asp-action="FriendsList">Lista znajomych</a>
                                    <a class="dropdown-item" asp-area="User" asp-controller="Recommendations" asp-action="Index">Rekomendacje znajomych</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="User" asp-controller="Search" asp-action="FilterMoviesForm">Szukaj filmu</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="User" asp-controller="Ratings" asp-action="Index">Twoje oceny</a>
                            </li>
                        }
                        else if (User.IsInRole("User") && !User.IsInRole("Moderator"))
                        {
                            <a class="navbar-brand" asp-area="User" asp-controller="Movies" asp-action="Index">IBF</a>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="User" asp-controller="Movies" asp-action="Index">Filmy</a>
                            </li>                            
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="User" asp-controller="Stars" asp-action="Index">Gwiazdy</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="User" asp-controller="Ratings" asp-action="Index">Twoje oceny</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="friendshipDropdown" role="button" data-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
                                    Znajomi
                                </a>
                                <div class="dropdown-menu" aria-labelledby="friendshipDropdown">
                                    <a class="dropdown-item" asp-area="User" asp-controller="Friendships" asp-action="Index">Szukaj znajomego</a>
                                    <a class="dropdown-item" asp-area="User" asp-controller="Friendships" asp-action="FriendsList">Lista znajomych</a>
                                    <a class="dropdown-item" asp-area="User" asp-controller="Recommendations" asp-action="Index">Rekomendacje znajomych</a>
                                </div>
                            </li>
                             <li class="nav-item">
                                <a class="navbar-brand" asp-area="User" asp-controller="Search" asp-action="FilterMoviesForm">Szukaj filmu</a>
                            </li>
                           


                        }
                        else if (User.IsInRole("Moderator"))
                        {
                            <a class="navbar-brand" asp-area="Moderator" asp-controller="Movies" asp-action="Index">IBF</a>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Moderator" asp-controller="Movies" asp-action="Index">Filmy</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Moderator" asp-controller="VODs" asp-action="Index">VOD</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Moderator" asp-controller="Moods" asp-action="Index">Nastroje</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Moderator" asp-controller="Genres" asp-action="Index">Gatunki</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Moderator" asp-controller="Countries" asp-action="Index">Kraje</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Moderator" asp-controller="Stars" asp-action="Index">Gwiazdy</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="Moderator" asp-controller="Functions" asp-action="Index">Funkcje</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="friendshipDropdown" role="button" data-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
                                    Znajomi
                                </a>
                                <div class="dropdown-menu" aria-labelledby="friendshipDropdown">
                                    <a class="dropdown-item" asp-area="User" asp-controller="Friendships" asp-action="Index">Szukaj znajomego</a>
                                    <a class="dropdown-item" asp-area="User" asp-controller="Friendships" asp-action="FriendsList">Lista znajomych</a>
                                    <a class="dropdown-item" asp-area="User" asp-controller="Recommendations" asp-action="Index">Rekomendacje znajomych</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="User" asp-controller="Search" asp-action="FilterMoviesForm">Szukaj filmu</a>
                            </li>
                            <li class="nav-item"> 
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="Index">Usuń użytkownika</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="User" asp-controller="Ratings" asp-action="Index">Twoje oceny</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - IBF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <!-- CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>