MvcIBF/Areas/Admin/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcIBF.Data;
using MvcIBF.Models;
using MvcIBF.Models.ViewModels.MovieVM;
using MvcIBF.Repository.IRepository;

namespace MvcIBF.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MoviesController : Controller
    {
        private readonly IUnitOfWork _context;
        private IMapper _mapper;

        public MoviesController(IUnitOfWork context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET: Movies
        public async Task<IActionResult> Index(string searchString)
        {
            var movies = _context.Movie.GetAll();
            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.MovieTitle!.Contains(searchString));
            }
            var sortedMovies = movies.OrderBy(m => m.MovieTitle);
            var vm = _mapper.Map<List<MovieVM>>(sortedMovies);

            return View(vm);
        }

        public async Task<IActionResult> Details(int id)
        {
            if (_context.Movie.GetAll() == null)
            {
                return NotFound();
            }
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userId = claim.Value;
            var movie = _context.Movie
                .GetMovieVM(id);
            var vm = _mapper.Map<MovieVM>(movie);
            if (movie == null)
            {
                return NotFound();
            }
            var ratings = _context.Rating
      .GetRatingsByMovieId(id)
      .ToList();
            var currentUserRating = ratings
        .SingleOrDefault(r => r.ApplicationUserId == userId);
            movie.Rating = currentUserRating?.RatingValue ?? 0;
            movie.UserComment = currentUserRating?.Comment ?? "Brak komentarza";


            return View(movie);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Details(int id, int ratingValue, string comment)
        {
            if (_context.Movie.GetAll() == null)
            {
                return NotFound();
            }
            var movie = _context.Movie.GetMovie(id);
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userId = claim.Value;
            var user = _context.ApplicationUser.GetFirstOrDefault(u => u.Id == userId);
            var rating = _context.Rating
                .GetFirstOrDefault(r => r.ApplicationUserId == userId && r.MovieId == movie.MovieId);
            if (rating == null)
            {
                rating = new Rating
                {
                    ApplicationUserId = userId,
                    MovieId = movie.MovieId,
                    RatingValue = ratingValue,
                    Comment = comment,

                };

                _context.Rating.Add(rating);
                user.Ratings.Add(rating);
                movie.Ratings.Add(rating);
                _context.ApplicationUser.Update(user);
            }
            else
            {
                rating.RatingValue = ratingValue;
                rating.Comment = comment;
                _context.Rating.Update(rating);
            }

            _context.Save();

            return RedirectToAction("Details", new { id });
        }
        public async Task<IActionResult> FriendsRating(int id)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userId = claim.Value;
            var currentUser = _context.ApplicationUser.GetById(userId);
            var users = _context.ApplicationUser.GetAll();
            var currentFriends = _context.Friendship.GetUserFriendsById(userId);
            var ratings = new List<Rating>();
            foreach (var friend in currentFriends)
            {
                var rating = _context.Rating.GetRatingByUserIdAndMovieId(friend.Id, id);
                if (rating != null)
                {
                    ratings.Add(rating);
                }
            }
            if (ratings.Count == 0 || ratings == null)
            {
                ModelState.AddModelError("", "Twoi znajomi nie ocenili tego filmu");
                return View("EmptyFriendsRating");
            }
            else
            {
                return View(ratings.OrderBy(x=>x.ApplicationUser.UserName));
            }
        }
        public async Task<IActionResult> CreateRecommendation(int id)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userId = claim.Value;
            var currentUser = _context.ApplicationUser.GetById(userId);
            var users = _context.ApplicationUser.GetAll();
            var currentFriends = _context.Friendship.GetUserFriendsById(userId);
            var unseenFriends = new List<ApplicationUser>();

            foreach (var friend in currentFriends)
            {
                var friendship = _context.Friendship.GetFriendshipById(userId, friend.Id);
                var unseenFriendRating = _context.Rating.GetRatingByUserIdAndMovieId(friend.Id, id);
                var alreadyRecommendedFriends = _context.ApplicationUser.GetUsersRecommendations(friendship.FriendshipId, id);
                if (unseenFriendRating == null && alreadyRecommendedFriends == null)
                {
                    unseenFriends.Add(friend);
                }
            }
            if (unseenFriends.Count != 0)
            {
                ViewData["MovieId"] = id;
                return View("ChooseFriend", unseenFriends.OrderBy(x=>x.UserName));
            }
            else
            {
                return View("EmptyRecommendations");
            }
        }
        [HttpPost]
        public IActionResult Recommend(string friendId, int movieId, string? recommendation = null)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userId = claim.Value;
            var currentUser = _context.ApplicationUser.GetById(userId);
            var friend = _context.ApplicationUser.GetById(friendId);
            var friendship = _context.Friendship.GetFriendshipById(userId, friendId);

            var Recommendation = new Movie_Friendship
            {
                FriendshipId = friendship.FriendshipId,
                MovieId = movieId,
                Recommendation = recommendation
            };
            Recommendation.Friendship = friendship;
            _context.Recommendation.Add(Recommendation);
            friendship.Movie_Friendships.Add(Recommendation);
            _context.Save();
            return RedirectToAction("Index");
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            var vods = _context.VOD.GetAll();
            var selectListVods = new List<SelectListItem>();
            foreach (var item in vods)
            {
                selectListVods.Add(new SelectListItem(item.VodName, item.VodId.ToString()));
            }
            var moods = _context.Mood.GetAll();
            var selectListMoods = new List<SelectListItem>();
            foreach (var item in moods)
            {
                selectListMoods.Add(new SelectListItem(item.MoodName, item.MoodId.ToString()));
            }
            var genres = _context.Genre.GetAll();
            var selectListGenres = new List<SelectListItem>();
            foreach (var item in genres)
            {
                selectListGenres.Add(new SelectListItem(item.GenreName, item.GenreId.ToString()));
            }
            var countries = _context.Country.GetAll();
            var selectListCountries = new List<SelectListItem>();
            foreach (var item in countries)
            {
                selectListCountries.Add(new SelectListItem(item.CountryName, item.CountryId.ToString()));
            }
            var functions = _context.Function.GetAll();
            var stars = _context.Star.GetAll();
            var selectListStars= new List<Star>();
            foreach (var item in stars)
            {
                var fullname = item.FirstName + " " + item.LastName;
            }
            var selectedStars = new List<int>();
            var selectedStarsList = new List<List<int>>();
            foreach (var item in functions)
            {
                
                selectedStarsList.Add(selectedStars);
            }
            var vm = new MovieVM
            {
                VODsList = selectListVods,
                MoodsList = selectListMoods,
                GenresList = selectListGenres,
                CountriesList = selectListCountries,
                URLs= new List<string>(),
                Functions= functions,
                StarsList= stars,
                SelectedStarsFunction= selectedStarsList
                
            };
            return View(vm);
        }

        // POST: Movies/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MovieVM vm)
        {
            if (ModelState.IsValid)
            {
                
                _context.Movie.AddMovieWithProperties(vm);
                var model = _mapper.Map<Movie>(vm);
                
                _context.Save();
                
                return RedirectToAction(nameof(Index));
            }

MvcIBF/Areas/User/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcIBF.Data;
using MvcIBF.Models;
using MvcIBF.Models.ViewModels.MovieVM;
using MvcIBF.Repository.IRepository;

namespace MvcIBF.Areas.User.Controllers
{
    [Area("User")]
    public class MoviesController : Controller
    {
        private readonly IUnitOfWork _context;
        private IMapper _mapper;

        public MoviesController(IUnitOfWork context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET: Movies
        public async Task<IActionResult> Index(string searchString)
        {
            var movies = _context.Movie.GetAll();
            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.MovieTitle!.Contains(searchString));
            }
            var sortedMovies = movies.OrderBy(m => m.MovieTitle);
            var vm = _mapper.Map<List<MovieVM>>(sortedMovies);

            return View(vm);
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (_context.Movie.GetAll() == null)
            {
                return NotFound();
            }
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userId = claim.Value;
            var movie = _context.Movie
                .GetMovieVM(id);
            var vm = _mapper.Map<MovieVM>(movie);
            if (movie == null)
            {
                return NotFound();
            }
            var ratings = _context.Rating
      .GetRatingsByMovieId(id)
      .ToList();
            var currentUserRating = ratings
        .SingleOrDefault(r => r.ApplicationUserId == userId);
            movie.Rating = currentUserRating?.RatingValue ?? 0;
            movie.UserComment = currentUserRating?.Comment ?? "Brak komentarza";
            

            return View(movie);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Details(int id, int ratingValue, string comment)
        {
            if (_context.Movie.GetAll() == null)
            {
                return NotFound();
            }           
            var movie = _context.Movie.GetMovie(id);            
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userId = claim.Value;
            var user = _context.ApplicationUser.GetFirstOrDefault(u => u.Id == userId);
            var rating = _context.Rating
                .GetFirstOrDefault(r => r.ApplicationUserId == userId && r.MovieId == movie.MovieId);
            if (rating == null)
            {
                rating = new Rating
                {
                    ApplicationUserId = userId,
                    MovieId = movie.MovieId,
                    RatingValue = ratingValue,
                    Comment = comment,
                    
                };
                
                _context.Rating.Add(rating);
                user.Ratings.Add(rating);
                movie.Ratings.Add(rating);
                _context.ApplicationUser.Update(user);                
            }
            else
            {
                rating.RatingValue = ratingValue;
                rating.Comment = comment;
                _context.Rating.Update(rating);
            }

            _context.Save();

            return RedirectToAction("Details", new { id });
        }
        public async Task<IActionResult> FriendsRating(int id)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userId = claim.Value;
            var currentUser = _context.ApplicationUser.GetById(userId);
            var users = _context.ApplicationUser.GetAll();
            var currentFriends = _context.Friendship.GetUserFriendsById(userId);
            var ratings = new List<Rating>();
            foreach(var friend in currentFriends)
            {
                var rating = _context.Rating.GetRatingByUserIdAndMovieId(friend.Id, id);
                if (rating != null)
                {
                    ratings.Add(rating);
                }
            }
            if (ratings.Count == 0 || ratings == null)
            {
                ModelState.AddModelError("", "Twoi znajomi nie ocenili tego filmu");
                return View("EmptyFriendsRating");
            }
            else
            {
                return View(ratings.OrderBy(x => x.ApplicationUser.UserName));
            }
        }
        public async Task<IActionResult> CreateRecommendation(int id)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userId = claim.Value;
            var currentUser = _context.ApplicationUser.GetById(userId);
            var users = _context.ApplicationUser.GetAll();
            var currentFriends = _context.Friendship.GetUserFriendsById(userId);
            var unseenFriends = new List<ApplicationUser>();
            
            foreach (var friend in currentFriends)
            {
                var friendship = _context.Friendship.GetFriendshipById(userId, friend.Id);
                var unseenFriendRating = _context.Rating.GetRatingByUserIdAndMovieId(friend.Id, id);
                var alreadyRecommendedFriends = _context.ApplicationUser.GetUsersRecommendations(friendship.FriendshipId, id);
                if (unseenFriendRating == null && alreadyRecommendedFriends ==null)
                {
                    unseenFriends.Add(friend);
                }
            }
            if (unseenFriends.Count != 0)
            {
                ViewData["MovieId"] = id;
                return View("ChooseFriend", unseenFriends.OrderBy(x => x.UserName));
            }
            else
            {
                return View("EmptyRecommendations");
            }
        }
        [HttpPost]
        public IActionResult Recommend(string friendId, int movieId, string? recommendation = null)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userId = claim.Value;
            var currentUser = _context.ApplicationUser.GetById(userId);
            var friend = _context.ApplicationUser.GetById(friendId);
            var friendship = _context.Friendship.GetFriendshipById(userId, friendId);
            
            var Recommendation = new Movie_Friendship
            {
                FriendshipId = friendship.FriendshipId,                
                MovieId = movieId,
                Recommendation = recommendation
            };
            Recommendation.Friendship = friendship;            
            _context.Recommendation.Add(Recommendation);
            friendship.Movie_Friendships.Add(Recommendation);                        
            _context.Save();
            return RedirectToAction("Index");
        }
    }
}

MvcIBF/Areas/User/Views/Movies/Details.cshtml
@model MvcIBF.Models.ViewModels.MovieVM.MovieVM

@{
    ViewData["Title"] = "Details";
}

<h1>Szczegóły</h1>

<div>
    <h4>Film</h4>
    <hr />
    <div class="col-md-4">
        @if (@Model.URLs.Count() != 0)
        {
            <img src="@Model.URLs.First()" width="100%" alt="@Model.MovieTitle">
        }
        else
        {
            <img src="https://protkd.com/wp-content/uploads/2017/04/default-image.jpg" width="100%" alt="@Model.MovieTitle">
        }
    </div>
    <div>
        @if (@Model.AverageRating != 0)
        {
            <p>Średnia ocen: @Model.AverageRating.ToString("0.00")</p>
        }
        else
        {
            <p>Brak ocen</p>
        }
    </div>
    <div>
        @if (@Model.Rating != 0)
        {
            <p>Twoja ocena: @Model.Rating</p>
            <p>Twój komentarz do oceny: @Model.UserComment</p>
        }
        else
        {
            <p>Twoja ocena: Brak</p>
        }
    </div>
    @if (User.Identity.IsAuthenticated)
    {
        <div>
            <a asp-action="FriendsRating" asp-route-id="@Model.MovieId">Wyświetl oceny znajomych</a>
        </div>
        <div>
            <a asp-action="CreateRecommendation" asp-route-id="@Model.MovieId">Zarekomenduj film znajomemu</a>
        </div>
        <h3>Oceń film:</h3>
        <form asp-controller="Movies" asp-action="Details" method="post">
            <input type="hidden" name="id" value="@Model.MovieId" />
            <div>
                <label for="ratingValue">Ocena:</label>
                <select name="ratingValue" id="ratingValue">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                </select>
            </div>
            <div>
                <label for="comment">Kometarz:</label>
                <textarea name="comment" id="comment"></textarea>
            </div>
            <button type="submit">Oceń</button>
            @Html.AntiForgeryToken()
        </form>
    }
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MovieTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MovieTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Runtime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Runtime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MovieDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MovieDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VodNames)
        </dt>
        @*<dd class = "col-sm-10">
        @Html.DisplayFor(model => model.VodNames)
        </dd>*@
        @if (Model.VodNames.Count() != 0)
        {
            <dd class="col-sm-10">

                @foreach (var item in Model.VodNames)
                {
                    @item

                    <text>&nbsp;</text>

                }
            </dd>
        }
        else
        {
            <dd class="col-sm-10">Brak danych</dd>
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MoodNames)
        </dt>
        @if (Model.MoodNames.Count() != 0)
        {
            <dd class="col-sm-10">
                @foreach (var item in Model.MoodNames)
                {
                    @item

                    <text>&nbsp;</text>
                }
            </dd>
        }
        else
        {
            <dd class="col-sm-10">Brak danych</dd>
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GenreNames)
        </dt>
        @if (Model.GenreNames.Count() != 0)
        {
            <dd class="col-sm-10">
                @foreach (var item in Model.GenreNames)
                {
                    @item

                    <text>&nbsp;</text>
                }
            </dd>
        }
        else
        {
            <dd class="col-sm-10">Brak danych</dd>
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CountryNames)
        </dt>
        @if (Model.CountryNames.Count() != 0)
        {
            <dd class="col-sm-10">
                @foreach (var item in Model.CountryNames)
                {
                    @item

                    <text>&nbsp;</text>
                }
            </dd>
        }
        else
        {
            <dd class="col-sm-10">Brak danych</dd>
        }
    </dl>
    @if (Model.URLs != null)
    {
        @if (Model.URLs.Count() > 1)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.URLs)
            </dt>
            <div class="col-md-4">
                @foreach (var item in Model.URLs)
                {
                    <img src="@item" width="50%" alt="@Model.MovieTitle">
                }

            </div>
        }
        else if (Model.URLs.Count() != 0)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.URLs)
            </dt>
            <img src="@Model.URLs.First()" width="50%" alt="@Model.MovieTitle">
        }

    }
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .profile-image {
            width: 150px;
            height: 150px;
            max-width: 100%;
            max-height: 100%;
            object-fit: cover;
            border-radius: 50%;
        }

        .name-column {
            white-space: nowrap;
        }
    </style>
    @if (Model.StarsFunctionsList.Count() != 0)
    {
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StarsFunctionsList)
        </dt>
        <table>
            <thead>
                <tr>
                    <th>Zdjęcie profilowe</th>
                    <th>Gwiazda</th>
                    <th>Funkcja</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var Movie_Star_Function in Model.StarsFunctionsList)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="profile-image" src="@Movie_Star_Function.Star.ProfilePictureURL" alt="@Movie_Star_Function.Star.LastName" />
                        </td>
                        <td class="align-middle name-column">@Movie_Star_Function.Star.FirstName @Movie_Star_Function.Star.LastName</td>
                        <td class="align-middle">@Movie_Star_Function.Function.FunctionName</td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>
<div>
    <a asp-action="Index">Wróć</a>
</div>

MvcIBF/Areas/User/Views/Movies/FriendsRating.cshtml
@model IEnumerable<MvcIBF.Models.Rating>

@{
    ViewData["Title"] = ">Oceny znajomych";
}

<h1>Oceny znajomych</h1>


<table class="table">
    <thead>
        <tr>
            <th>Zdjęcie profilowe</th>
            <th>Znajomy</th>            
            <th>
                @Html.DisplayNameFor(model => model.RatingValue)
            </th>

            <th>@Html.DisplayNameFor(model => model.Comment)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (!string.IsNullOrEmpty(item.ApplicationUser.ProfilePictureUrl))
                    {
                        <img src="@item.ApplicationUser.ProfilePictureUrl" alt="Profile Picture" style="max-width: 10%; max-height: 10%;" />
                    }
                    else
                    {
                        <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__340.png" alt="Default Profile Picture" style="max-width: 10%; max-height: 10%;" />
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.Email)
                </td>               
                <td>
                    @Html.DisplayFor(modelItem => item.RatingValue)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comment)
                </td>                
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Index">Wróć</a>
</div>

MvcIBF/Areas/User/Views/Movies/Index.cshtml
@model IEnumerable<MvcIBF.Models.ViewModels.MovieVM.MovieVM>

@{
     ViewBag.Title = "Movies";
}

<h1>Filmy</h1>

    <form asp-controller="Movies" asp-action="Index">
        <p>
            Tytuł: <input type="text" name="SearchString" />
            <input type="submit" value="Filter" />
        </p>
    </form>
<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.MovieTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Runtime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MovieDescription)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MovieTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Runtime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MovieDescription)
            </td>
            <td>
            
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.MovieId">Szczegóły</a>
            </td>
        </tr>
}
    </tbody>
</table>